### ISSUE TITLE
Warning: The `set-output` command is deprecated

### ISSUE THREAD

**Issue by SamantazFox** [crystal-lang/install-crystal#16]
We've been recently getting the following message in our CI:

> Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

It happens after every step of the `Run crystal-lang/install-crystal@v1.6.0` action (looking at the changelog shows that 1.7.0 didn't fix the problem).

**Comment by oprypin** [comment]
What- so you didn't even try the latest version? It fixes it

**Comment by SamantazFox** [comment]
Ooops, yeah, sorry :/
